### PR TITLE
[docs]: add async/await guide

### PR DESCRIPTION
**Pull request by Rossh87**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. The two fields below are mandatory.

If you're making a change to documentation, do **not** modify a `.html` file directly. Instead find the corresponding `.pug` file or test case in the `test/docs` directory.

**Summary**

Adds async/await guide to Mongoose docs

**Examples**

Async/Await now appears under 'Guides' in sidebar nav of documentation.

### CODE REVIEW

**Comment by Rossh87** [comment]
Sure, done!  Build failing, but looks like it's for unrelated reasons.

**Comment by vkarpov15** [comment]
Sorry, but can you just make a separate PR that just modifies `.pug` files, not any HTML? It looks like you've deleted `docs/api.html` and added `yarn.lock`, among other unintentional changes.

**Comment by Rossh87** [comment]
Sure!  Done.  Sorry for the delay, I've been out of town.

**Comment by vkarpov15** [comment]
No worries, thanks for your patience :+1:

**Pull request closed without merging**
