### PR TITLE
Boolean strict mode #5211

### PR DESCRIPTION
**Pull request by c0d0g3n**
See #5211 and #4245. Strict mode (`strict: true`) throws cast error if input is not a boolean representation. Not backwards breaking as new behavior is opt-in via option. Unit test for accepted values included. Could not add documentation because `make docs` errors (should go into separate issue?).

### CODE REVIEW

**Comment by vkarpov15** [comment]
So first your branch is very confusing, hard to tell what actually changed. But looking at d57351e, I don't think I can merge this. `strict: true` is on by default, and already has its own semantics. I don't want to conflate new behavior with strict mode. I think a [custom schema type](http://mongoosejs.com/docs/customschematypes.html) or a plugin that replaces mongoose's `Boolean.prototype.cast` function would be more appropriate in this case.

**Comment by c0d0g3n** [comment]
Apologies, I indeed made a bit of a mess. For clarification, d57351e57077047b2deafaa5e786f7ae6e033728 adds the strict option, ede9c64d0d06e22312656bdd34d612ba823a400a adds a unit test. 8212b49bb19d14c5ae2bd5587a63a5a07431f508 (getting up-to-date) was a pull/merge (I don't know anymore) from upstream, which in hindsight was probably not the way things go (Sorry, it's my first pr ever :)). I can create a new, proper pull request if you want.

You're probably referring to this: http://mongoosejs.com/docs/guide.html#strict? I thought it wouldn't be a problem because that option only applies to schemas, whereas the pr operates only on paths of type `Boolean`. How about changing `strict` in this pr to `strictBool` or `strictCast` to avoid confusion?

**Comment by vkarpov15** [comment]
I'm not very excited to add yet another option to schemas, that's fast becoming a dumping ground for 4.x behaviors that we want to get rid of. However, I can stomach it, `strictBool` it is :)

**Comment by c0d0g3n** [comment]
I understand that it would be more elegant to update behavior in 5.0, if that is what you mean. I've a workaround published [here](https://gist.github.com/c0d0g3n/40b4b62041969abfafe4199c4101c047) for now. I was also thinking if it would be useful that users can customize the values that are accepted as true and false, because in extreme cases users may not want to validate f.i. `'true'` as `true` either. (Maybe we should even abolish converting altogether and introduce something like Wordpress filter hooks.) This may be a little far fetched though.

Anyway, just give me a shout if you still want a clean pr with `strictBool` and docs.

**Comment by vkarpov15** [comment]
Users can customize the values by overwriting the boolean type's `cast()` function, I don't see a need to add any more abstractions there currently. However, if you're still willing to do a clean `strictBool` PR I'd be happy to merge it :+1:

**Pull request closed without merging**
