### PR TITLE
Feature/gh3034 this error

### PR DESCRIPTION
**Pull request by taxilian**
I have made one change that may be controversial, and I'm willing to change it if you like.  I dislike checking if doc === global just because in principle there could be cases where global isn't what is expected; we don't actually care specifically if it is global, we care if it isn't the object we expect.  

Therefore, instead of checking against global I'm checking to see if the features / objects we need are present.

I see this somewhat akin to the difference between checking for features in a web browser vs checking which web browser we're in -- feature checking is much more flexible =]

### CODE REVIEW

**Comment by vkarpov15** [comment]
You're right that checking for global is gnarly in the extreme. Admittedly it's a bit of a hack because of the special case when you do `Function.call(null)`. The approach right now of checking for certain properties is pretty brittle. How about, instead, we use `doc instanceof Document`?

**Comment by taxilian** [comment]
I like it -- I'll update when I get home tonight.

**Comment by taxilian** [comment]
Okay, I've updated both of those spots and they still pass the tests.  I feel like this is actually the correct fix -- good call!

**Comment by vkarpov15** [comment]
Great job @taxilian, thanks

**Pull request merged**
