### PR TITLE
fix(document): fix ObjectId conversion for external schemas

### PR DESCRIPTION
**Pull request by coyotte508**
**Summary**

When dealing with external schemas, i.e. a mongoose schema created inside another module, `instanceOf` may not work.

This results in the value of ObjectIds in the schema being converted to strings when saving to the database.

**Examples**

I have a monorepo project with pnpm. One module `lib` contains a schema, which I use to create a model in my program. 

Both my program and the imported `lib` module have the same `bson`, `mongoose` and `mongodb` versions.

### CODE REVIEW

**Comment by coyotte508** [comment]
Honestly not sure why tests fail. I readded the removed code in the second commit.

Another way to discriminate against `ObjectId` would be to check `obj._bsonType ===  "ObjectID"`.

**Comment by Uzlopak** [comment]
Can you search the whole codebase for instanceof ObjectId, please?

**Comment by coyotte508** [comment]
> Can you search the whole codebase for instanceof ObjectId, please?

I didn't replace a few:

- in `cast/objectid.js`, it's not necessary (but could improve performance)
- in the docs, not familiar enough to know what to do there

Same for `Decimal128`

**Review by AbdelrahmanHafez — APPROVED** [review]
LGTM, thanks! 👍

**Comment by Uzlopak** [comment]
LGTM!

**Review by Uzlopak — APPROVED** [review]

**Pull request merged**
