### PR TITLE
Documentation: typo fix

### PR DESCRIPTION
**Pull request by sushiljainam**
change the word `opts` to `ops` in documentation

**Summary**

Only change to a documentation typo

**Examples**

### CODE REVIEW

**Comment by Uzlopak** [comment]
should be actually the other way round. all opts should be ops

**Review by Uzlopak — CHANGES_REQUESTED** [review]
Please change all `opts. `to `ops.`

**Comment by sushiljainam** [comment]
All `opts` changed to `ops` 
@Uzlopak Please review now.

**Review by Uzlopak — APPROVED** [review]
Perfect. Thanks

**Pull request merged**
