### PR TITLE
feat(schema+types): add `{ errorHandler: true }` option to Schema `post()` for better TypeScript support

### LINKED ISSUE #12583: Typescript: Error Handling Middleware callback function params are implicitly set to 'any'.
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.6.7

### Node.js version

18.11.0

### MongoDB version

6.0.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Issue

I'm following this documentation [[Error Handling Middleware](https://mongoosejs.com/docs/middleware.html#error-handling-middleware)](https://mongoosejs.com/docs/middleware.html#error-handling-middleware), and TypeScript does not infer the error middleware function arguments if three parameters are given.

```
userSchema.post('save', function (error, doc, next) { <------ All params implicitly has an 'any' type.
  if (error.name === 'MongoServerError' && error.code === 11000) {
    next(new Error('There was a duplicate key error'))
  } else {
    next()
  }
})
```

I know it is possible to set those types explicitly. However, it will lead to a bunch of boilerplate code, which should be inferred from `ErrorHandlingMiddlewareFunction` type.

My tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "rootDir": "src",
    "outDir": "dist",
    "lib": [
      "es6"
    ],
    "removeComments": false,
    "strict": true,
    "declaration": true,
    "declarationDir": "types",
    "skipLibCheck": true,
    "esModuleInterop": true
  },
  "include": [
    "src",
    "test"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

### LINKED ISSUE #12595: Model.bulkWrite updateOne.update and updateMany.update type UpdateFilter<TSchema> should be compatible with Model.updateOne and Model.updateMany type UpdateQuery<T>
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.0

### Node.js version

16.17.0

### MongoDB server version

5.0.5

### Typescript version (if applicable)

4.8.4

### Description

same issue as #11911

### Steps to Reproduce

```ts
import mongoose, { UpdateQuery } from 'mongoose';
const { Schema, model } = mongoose;

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  interface IAnimal {
    name?: string;
  }

  const animalSchema = new Schema<IAnimal>({
    name: { type: String }
  });

  const Animal = model<IAnimal>('Animal', animalSchema);

  const writeOperations = ['foo', 'bar', 'baz'].map(name => {
    const changes: UpdateQuery<IAnimal> = {}

    if (name === 'foo') {
      changes.name = name.repeat(2);
    } else {
      changes.name = name.repeat(4);
    }

    return {
      updateOne: {
        filter: { name },
        update: changes
      }
    }
  })

  await Animal.bulkWrite(writeOperations);
}
run();
```

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
  }
}
```

### Expected Behavior

Model.bulkWrite (updateOne.update || updateMany.update) UpdateFilter<TSchema> and Model.updateOne UpdateQuery<T> should be compatible

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #12583

**Summary**

Requires https://github.com/mongoosejs/kareem/pull/34 . You can now do `schema.post('save', { errorHandler: true }, async function(err) { ... })`. This means you can use error handling middleware without explicitly listing out arguments, and also makes TypeScript better able to infer the type of params to error handling middleware.

**Examples**

### CODE REVIEW

**Comment by hasezoey** [comment]
This PR maybe should be changed to a "Draft" (WIP) PR, so that it can not be accidentally merged (even if tests are failing)

**Comment by vkarpov15** [comment]
@hasezoey good suggestion. But can you please review this PR and https://github.com/mongoosejs/kareem/pull/34 anyway? This PR is ready to go, just hard to test because it requires a PR from a separate repo. Tests pass locally, I just want to make sure the API design makes sense.

**Comment by hasezoey** [comment]
> But can you please review this PR

will try, when the required lower PR is merged and this PR is updated to actually use that package instead of relative path

**Review by hasezoey — APPROVED** [review]
LGTM

and "finally" kareem shipped a new version which cut the size in less than half (thanks to not including useless files like tests anymore)
for reference, `2.4.1` was `109 kB` and `2.5.0` is `38.9 kB` (bundle size as reported by npm)

**Pull request merged**
