### PR TITLE
Call _markModified in splice array method

### PR DESCRIPTION
**Pull request by josegl**
In the implementation of the other array methods that mutate the array,
the _markModified function is called, but in the splice method it
wasn't.

This leads to do not detect changes that happen in arrays when the splice method is used.

### CODE REVIEW

**Review by hasezoey — CHANGES_REQUESTED** [review]
A test would be good so that in the future this does not silently break again

**Review by AbdelrahmanHafez — CHANGES_REQUESTED** [review]
Please add a test to demonstrate the issue you're facing and prevent future regression.

**Comment by josegl** [comment]
@hasezoey, @AbdelrahmanHafez How could I test this and where. It seems that there are a bunch of places where tests are placed, but I cannot find the most suitable place to put it. And to be honest I'm not very sure how could I test this. Could you please help me in that regard?

**Comment by AbdelrahmanHafez** [comment]
@josegl 
You can try `test\types.array.test.js` to write a unit test that tests the array class directly, or it might actually be better to test how you'd run it in your apps in `test\document.test.js` by creating a schema, a model, and a document, mark the document as not modified, and then `splice`, and then assert that it's marked as modified.

**Review by vkarpov15 — APPROVED** [review]
Nice catch, thanks. I'll wait until you've added the tests to merge.

**Comment by josegl** [comment]
I've added the test as you guys suggested.

**Comment by hasezoey** [comment]
> I've added the test as you guys suggested.

looks good, though maybe run a `npm run lint --fix` and push that too

**Review by hasezoey — APPROVED** [review]
LGTM

**Review by Uzlopak — APPROVED** [review]
LGTM

**Pull request merged**
