### PR TITLE
Replace internal pluralize with pluralize-mongoose package

### LINKED ISSUE #3382: extract pluralize from utils.js
`lib/utils.js` that there is a section for pluralizing words.
and a deprecation notice that refers back to #1350.

Is this something that could now be completely deprecated and removed?
Or if the functionality needs to stay, could a library like https://github.com/blakeembrey/pluralize be used rather than maintaining an internal implementation?

Thoughts? :thought_balloon:

### PR DESCRIPTION
**Pull request by ChristianMurphy**
resolves #3382
this is a non-breaking version of #3398

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@vkarpov15 would you like me to transfer ownership of [pluralize-mongoose](https://github.com/ChristianMurphy/pluralize-mongoose) to you or to the Automattic organization?
Or leave it where it is?

**Comment by vkarpov15** [comment]
Just add me as a contributor on npm (vkarpov15) and github, that should be sufficient for now.

**Comment by ChristianMurphy** [comment]
:+1: done

**Comment by vkarpov15** [comment]
Merged and released. Thanks @ChristianMurphy  :beers:

**Comment by ChristianMurphy** [comment]
Great, Thanks! :beers:

**Comment by tejasmanohar** [comment]
@vkarpov15 @ChristianMurphy Where has [pluralize-mongoose](https://www.npmjs.com/package/pluralize-mongoose) gone? O.o

**Comment by vkarpov15** [comment]
@tejasmanohar we deleted it. Since we ended up reverting the pluralization changes re: #3490, there's no need to have that package floating around. Are you having an issue?

**Pull request merged**
