### PR TITLE
Omit id field in lean document typings

### PR DESCRIPTION
**Pull request by tbhaxor**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. The two fields below are mandatory.

If you're making a change to documentation, do **not** modify a `.html` file directly. Instead find the corresponding `.pug` file or test case in the `test/docs` directory.

**Summary**

Closes https://github.com/Automattic/mongoose/issues/10345

**Examples**

Screenshot_20210618_193841

### CODE REVIEW

**Review by AbdelrahmanHafez — APPROVED** [review]

**Comment by vkarpov15** [comment]
Realistically I don't think we can merge this for the same reasons I described here: https://github.com/Automattic/mongoose/issues/10282#issuecomment-853103354 . Any document with a user-defined `id` property will lose the `id` property in the return value from `toObject()`

```typescript
import { model, Schema } from 'mongoose';

interface User {
  name: string;
  id: number;
}

const UserModel = model<User>('User', new Schema({ name: String, id: Number }));

const doc = new UserModel({ name: 'test', id: 42 });

const leanDoc = doc.toObject();
leanDoc.id = 43; // Property 'id' does not exist on type 'LeanDocument<User & Document<any, any>>'.
```

I think the better solution would be to pass `User` rather than `User & Document` internally to `LeanDocument`, and have `LeanDocument` avoid stripping document properties from types that don't `extends Document`. What do you think @tbhaxor ?

**Comment by tbhaxor** [comment]
> pass `User` rather than `User & Document`

@vkarpov15  It seems reasonable to me

**Comment by vkarpov15** [comment]
I think that should be up to the end user to add `_id` and `__v` to their document interface, if they choose to use them.

```typescript
interface User {
  _id: mongoose.Types.ObjectId;
  name: string;
}
```

You can disable `_id` and `versionKey` from the schema constructor options, so technically Mongoose can't know whether the document has `_id` and `__v` at compile time without the end user telling us so.

**Comment by tbhaxor** [comment]
@vkarpov15 Again, your point made sense 😄

**Comment by tbhaxor** [comment]
So, a Leaned Document **MUST** return the generic type passed

**Pull request closed without merging**
