### PR TITLE
Update virtuals.html

### PR DESCRIPTION
**Pull request by Psarna94**
I think the grammar here is not entirely correct. made suitable changes

### CODE REVIEW

**Comment by vkarpov15** [comment]
Thanks! `virtuals.html` is compiled code though, can you update `docs/virtuals.jade` with these changes instead?

**Comment by Psarna94** [comment]
On it

**Comment by Psarna94** [comment]
Cant find any file by the name virtuals.jade. 
screen shot 2015-12-04 at 11 10 46 am

**Comment by vkarpov15** [comment]
Ah you're right, these are the old legacy docs...

**Pull request merged**
