### PR TITLE
Support isAsync option for validators

### LINKED ISSUE #4290: Add explicit `validateAsync` function for schemas, deprecate implicit async validators
Re: #4084, #4064

### PR DESCRIPTION
**Pull request by vkarpov15**
Fix #4290

### CODE REVIEW

**Comment by varunjayaraman** [comment]
Looks good to me. Are there tests for this bad boy yet?

**Comment by vkarpov15** [comment]
Nope other than the docs test. Will add a couple more before I merge this one :+1:

**Comment by crossman** [comment]
@vkarpov15 It looks like this option isn't fully accessible when adding a validator from a plugin.

http://mongoosejs.com/docs/api.html#schematype_SchemaType-validate

The documentation for that still says that synchronicity is assumed based on the function signature. And after looking at the [code](https://github.com/Automattic/mongoose/blob/91866a8cff78b92d1f60e973e99910c6e8fdb612/lib/schematype.js#L452) it seems like `isAsync` can be set by passing in an object for the `errorMsg` param, but only if the `type` param is omitted.

I'm just wondering if `SchemaType#validate` needs to be updated to make `isAsync` easier to set or if it is intended that you should only be able to set it when passing an object to the `errorMsg` param without setting the `type`.

**Comment by vkarpov15** [comment]
Thanks for the suggestion @crossman , will fix asap.

**Comment by crossman** [comment]
Thank! I greatly appreciate your work.

**Comment by vkarpov15** [comment]
@crossman actually it's pretty easy, just do this:

```javascript
schema.path('name').validate({
  isAsync: true,
  validator: function(val, cb) { /* ... */ },
  message: 'blah' // custom message is optional
});
```

IMO much cleaner than relying on positional args anyway

**Comment by crossman** [comment]
I actually ran into this because a plugin I was using triggered the deprecation message and didn't expose enough of its usage of `validate` for me to do something like what you suggested. Which led me into a deep dive of figuring out it if it was possible for me to solve the deprecation without waiting for the plugin to release an update. The plugin has since been updated anyway, so I guess everything is solved. Just lead me to some questions on intended use.

**Comment by vkarpov15** [comment]
Glad you figured it out and sorry about the trouble. There have just been an awful lot of hard-to-debug issues with people plugging in outside functions into `validator` and not checking the function arity carefully enough, so we want to discourage this behavior going forward. Let me know if you run into any other plugins that need to upgrade their usage :+1:

**Pull request merged**
