### PR TITLE
enhancement(schemaType): pass document to default functions

### LINKED ISSUE #9633: enhancement: pass document to default functions
Currently when a path has `default` set to a function, we can access the document via `this`, would be nice if the document gets passed as an argument to the function, similar to what we've done to `required` validator in https://github.com/Automattic/mongoose/issues/9433
```js
let documentIsThis;
let documentFromDefault;
const userSchema = new Schema({
  name: { type: String },
  age: {
    type: Number,
    default (doc) {
      // should evaluate to true so people can use arrow functions
      documentIsThis = doc === this;
     documentFromDefault = doc;
    }
  }

});

const User = mongoose.model('User', userSchema);

new User({ name: 'Hafez' });

assert.equal(documentIsThis, true);
assert.equal(documentFromDefault.name, 'Hafez');
```

### PR DESCRIPTION
**Pull request by AbdelrahmanHafez**
fixes #9633

### CODE REVIEW

**Review by vkarpov15 — APPROVED** [review]
Thanks :+1:

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez I'm going to have to revert this. There are a couple cases in our tests where we use functions that rely on arguments as defaults. For example:

```javascript
const schema = new Schema({
  myId: {
    type: 'ObjectId',
    default: mongoose.Types.ObjectId
  }
}); 
```

This change will mean Mongoose calls `mongoose.Types.ObjectId` with `doc` as the first argument. So this change is unfortunately a little too risky for a patch release. We can make this change for v6.0.

**Comment by AbdelrahmanHafez** [comment]
Ah yes, I didn't think of that.

I actually think now we're better off leaving things as is to avoid incorrectly passing the document as an argument to functions that do not necessarily expect the document.

For example, in our orders models we save `VATPercentage` which expects some parameters.

```js
VATPercentage: {
  type: Number,
  default: VATHelper.getVatPercentage
}
```

This would break if we pass any arguments to it since it expects the first argument to be a date.

```js
// vat.helper.js

const firstOfJuly2020 = new Date('2020-07-01');

module.exports = {
  // passing doc here would likely break the function
  getVatPercentage(date = new Date()) {
    if (date >= firstOfJuly2020) {
       return 0.15;
    }

    return 0.1;
 }
}
```

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 Do you think we should add this as a breaking change in v6.0 or leave things as is? I can see arguments on both sides, what do you think?

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez I'm leaning towards putting this in 6.0. Not 100% convinced, but I think consistency with other cases where we pass `doc` as the first parameter and allowing arrow functions for defaults is more important here. We can add workarounds for some common cases, like `Date.now()` or `ObjectId()` to minimize breakage.

**Pull request merged**
