### PR TITLE
Fix #4761: findAndModify passRawResult with lean

### LINKED ISSUE #4761: findOneAndUpdate: passRawResult not transmitted if lean===true
This is evident by inspection of `Query._findAndModify`, where if `lean===true`, the `callback` is invoked without the `res` parameter:
```
Query.prototype._findAndModify = function(type, callback) {
...
    if (!opts.passRawResult) {
      res = null;
    }

    if (!options.populate) {
      return options.lean === true
          ? callback(null, doc)
          : completeOne(_this.model, doc, res, fields, _this, null, callback);
    }

    var pop = helpers.preparePopulationOptionsMQ(_this, options);
    pop.__noPromise = true;
    _this.model.populate(doc, pop, function(err, doc) {
      if (err) {
        return callback(err);
      }

      return options.lean === true
          ? callback(null, doc)
          : completeOne(_this.model, doc, res, fields, _this, pop, callback);
    });
```
I should be able to add a test repro and PR for this.

### PR DESCRIPTION
**Pull request by mhfrantz**
Fixes #4761

### CODE REVIEW

**Comment by vkarpov15** [comment]
Good catch, thanks :beers: :christmas_tree:

**Comment by evilive3000** [comment]
I  get into error handler when use `passRawResult` option.

**Comment by evilive3000** [comment]
If i get it right it seems like all callbacks with arity == 3 treats as error handlers?

https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L1108

**Comment by vkarpov15** [comment]
@evilive3000 can you please clarify? I don't quite understand.

**Comment by evilive3000** [comment]
```javascript
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

var schema = new Schema({
  name: {type: String}
});

const errorHandler = function (err, res, next) {
  console.log({err});
  next();
};

mongoose.connect();
mongoose.set('debug', true);
mongoose.Promise = global.Promise;

schema.post('save', errorHandler);
schema.post('update', errorHandler);
schema.post('findOneAndUpdate', errorHandler);
schema.post('insertMany', errorHandler);

Person = mongoose.model('Person', schema);
```

```javascript
Person.findOneAndUpdate({name: 'name'}, {}, {upsert: true}).exec();

// Mongoose: people.findAndModify({ name: 'name' }, [], { '$setOnInsert': { __v: 0 } }, { upsert: true, new: false, remove: false })

```

```javascript
Person.findOneAndUpdate({name: 'name'}, {}, {upsert: true, passRawResult: true}).exec();

// Mongoose: people.findAndModify({ name: 'name' }, [], { '$setOnInsert': { __v: 0 } }, { upsert: true, passRawResult: true, new: false, remove: false })
// { err: { _id: 585efadd2112a158cf7e4b15, name: 'name', __v: 0 } }
```

**Comment by mhfrantz** [comment]
@evilive3000 This seems like an issue independent of #4762, right?  There is no `lean` call, for example.

**Comment by evilive3000** [comment]
@mhfrantz, you're right. Should I have created new issue?

**Comment by mhfrantz** [comment]
@evilive3000 Sounds appropriate to have another issue opened (although I don't maintain this project).

**Comment by vkarpov15** [comment]
Yeah new issue is the way to go please

**Pull request merged**
