### PR TITLE
Fixed performance degradation

### PR DESCRIPTION
**Pull request by lbeschastny**
Fixed performance degradation mentionned in #2809  and caused by @6ce5a6c.

According to by benchmarks, it's not the only performance degradation, though it's the most severe one.

### CODE REVIEW

**Comment by lbeschastny** [comment]
Looks like it was already done in #2863 PR.

Well, at least the most important part.

**Comment by lbeschastny** [comment]
Rebased it to master.

Though, now this PR doesn't make much of a sense, since all important things was already done in #2863.

You could merge it anyway, or you could just close it, doesn't make much of a difference.

**Comment by lbeschastny** [comment]
And what's the problem with travis? It just randomly fails tests with `timeout of 2000ms exceeded` error.

Shouldn't you increase the timeout? Or is there some other problem causing tests to randomly hung?

**Comment by vkarpov15** [comment]
@lbeschastny Travis is pretty flakey, tests time out frequently. Haven't really investigated why, but I'm ok with running tests manually before releasing to double check.

**Pull request merged**
