### PR TITLE
enhancement: timestamps createdAt property immutable by default

### PR DESCRIPTION
**Pull request by IslandRhythms**
So there is a failing test, however I'm not sure If the test needs to be fixed or my solution needs to be changed. The test is gh-9105

### CODE REVIEW

**Review by AbdelrahmanHafez — CHANGES_REQUESTED** [review]
I'd say that such change is a breaking change and should not be included in a minor/patch release.
I think it's fine to set `createdAt` to be `immutable` by default, but if we choose to go that way, we need to move it to v6.0.

Also, would be neat to offer a global option to set `createdAt` to `false` for those who choose to.

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez you're right about this being potentially backwards breaking, I'll merge this into 6.0 just to be safe.

Any ideas for syntax re: setting `createdAt` to `false` globally? Maybe `mongoose.set('timestamps.createdAt', false)`?

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 
I'd go for `mongoose.set('timestamps.createdAt.immutable', false)`, otherwise it can mislead people to think that this option sets timestamps to *not* add a `createdAt` field.

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez would having an immutable `createdAt` break your code?

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 
No, but I am anticipating that someone out there is updating the value of createdAt, and it would really make their lives difficult.

We can ship this as an option to set immutable globally on createdAt, to be false by default in v5, then change it to true by default in v6.

**Review by miladezzat — APPROVED** [review]

**Pull request merged**
