### PR TITLE
Changed the code from 'await author.save()' to 'await story1.save()' …

### PR DESCRIPTION
**Pull request by SomSingh23**
## This pull request resolves the issue in the 'docs/populate.md' file. 

It replaces 'await author.save()' with 'await story1.save()' for clarity and correctness.

The motivation behind this change is to ensure that readers and code implementers encounter no errors while following the documentation and implementing the code simultaneously.

image

### CODE REVIEW

**Review by vkarpov15 — CHANGES_REQUESTED** [review]
The actual `await story1.save();` change is LGTM, but there's a bunch of unrelated changes in this PR. Looks like you're using some sort of code formatter that is automatically changing single quotes to double quotes and adding trailing commas: can you please undo all unrelated changes?

**Comment by SomSingh23** [comment]
> The actual `await story1.save();` change is LGTM, but there's a bunch of unrelated changes in this PR. Looks like you're using some sort of code formatter that is automatically changing single quotes to double quotes and adding trailing commas: can you please undo all unrelated changes?

yeah definitely

**Comment by SomSingh23** [comment]
@vkarpov15 I have made some modifications to the code. Could you please take a look at it?

**Review by vkarpov15 — APPROVED** [review]
Nice, thanks :+1:

**Comment by SomSingh23** [comment]
Thank you for merging my pull request.

**Pull request merged**
