### PR TITLE
Run lint as part of test

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Lint checks now run after tests.
Added a `npm run fix-lint` command to be able to automatically resolve most lint errors.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
set function style back to style requested [here](https://github.com/Automattic/mongoose/pull/3376#issuecomment-140816668)

**Comment by vkarpov15** [comment]
@ChristianMurphy thanks! Can you fix the outstanding lint issues? Looks like there's one unused variable and a couple issues with the browser entry points that we need to work around

**Comment by ChristianMurphy** [comment]
@vkarpov15 resolved lint warnings

**Comment by vkarpov15** [comment]
Thanks!

**Pull request merged**
