### PR TITLE
types(schematypes): use DocType for instance method this

### PR DESCRIPTION
**Pull request by pshaddel**
Fixes this issue: https://github.com/Automattic/mongoose/issues/13800

### CODE REVIEW

**Comment by pshaddel** [comment]
Right now instance method names does not have a typing(also the function we are passing) when user is passing InstanceMethod type. Let me know if I need to implement this too!

**Comment by ozzyonfire** [comment]
This looks great. Thanks for implementing it so quickly. I'm wondering if "this" should also expose the methods of a HydratedDocument. Like for example, "populate". 

There are a couple times I call `this.populate('item')` or something similar inside my instance method. And right now Typescript doesn't like that.

**Comment by pshaddel** [comment]
> 

Thanks for pointing that out. Just changed it to HydratedDocument.

**Comment by pshaddel** [comment]
I have pushed a new commit to fix the typescript failing test.

**Review by vkarpov15 — APPROVED** [review]
Thanks!

**Pull request merged**
