### PR TITLE
fix TypeScript declaration file

### LINKED ISSUE #11511: NX Next.JS app fails to build on v6.2.5
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
When I try to build my app, it throws this error:
```
../../node_modules/mongoose/types/cursor.ts:1:1
Type error: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} 
from "mod"', 'import d from "mod"', or another module format instead.

> 1 | import stream = require('stream');
    | ^
  2 |
  3 | declare module 'mongoose' {
  4 |   type CursorFlag = 'tailable' | 'oplogReplay' | 'noCursorTimeout' | 'awaitData' | 'partial';
```

Downgrading to v6.2.4 fixes the issue.

**If the current behavior is a bug, please provide the steps to reproduce.**

{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "commonjs",
    "lib": ["es2017", "dom", "ES2021.String", "ESNext.String"],
    "typeRoots": ["./@types", "./node_modules/@types"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "strictNullChecks": true,
    "baseUrl": ".",
    "jsx": "preserve",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "useDefineForClassFields": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsxImportSource": "@emotion/react"
  },
  "include": [
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "**/*.jsx",
    "next-env.d.ts",
    "../../libs/services/**/*",
    "../../libs/utils/general-utils/**/*",
    "../../libs/utils/react-utils/**/*"
  ],
  "exclude": ["**/*.spec.tsx", "**/*.spec.ts", "**/*.stories.tsx"]
}

**What is the expected behavior?**
App should build without issue.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

### LINKED ISSUE #11512: Does not compile with TypeScript
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Unable to compile due to message `Cannot find type definition file for 'mongoose/types/cursor'.`

**If the current behavior is a bug, please provide the steps to reproduce.**
Try compiling with any typescript project.

**What is the expected behavior?**
Compiles without errors.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 6.2.5

Seems the types cursor file is of the wrong file extension. Needs to change from `.ts` to `.d.ts`

https://github.com/Automattic/mongoose/blob/master/types/cursor.ts

### PR DESCRIPTION
**Pull request by SimonHausdorf**
**Summary**
Seems like there was a typo in `cursor.ts` file which should be a TypeScript declaration `cursor.d.ts`. It's blocking builds and tests for some people.

closes #11511
closes #11512

### CODE REVIEW

**Comment by sirily11** [comment]
did u try this fix with next js build?

**Review by m2vi — APPROVED** [review]

**Comment by Uzlopak** [comment]
Ah nice didn't see this PR. 

I am currently thinking how to avoid such a petty mistake for the future. Maybe adding a .gitignore in types folder and whitelisting only .d.ts files. Would be platform independent and you could not check in the file if it was a normal .ts file.

Anyway this PR lgtm!

**Comment by Uzlopak** [comment]
I added in #11516 logic to avoid again this type of regression.

**Review by vkarpov15 — APPROVED** [review]
Thanks, and sorry for the trouble!

**Pull request merged**
