### PR TITLE
chore(test.yml): add mongodb 6.0.0 to test

### LINKED ISSUE #12257: Does mongoose fully support mongodb 6.0?
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I know that mongodb 6.0 is out and it needs mongodb nodejs driver 4.8 or newer.
As I can see in package.json of mongoose, mongoose uses mongodb@4.8, so I guess mongoose can support mongodb 6.0.
I opened this issue to know whether mongoose is tested on mongodb 6.0 and can be used along with mongodb 6.0. Can anybody tell me? Thank you in advance.

### PR DESCRIPTION
**Pull request by hasezoey**
**Summary**

This PR adds mongodb 6.0.0 to the tests

fixes #12257

### CODE REVIEW

**Review by AbdelrahmanHafez — CHANGES_REQUESTED** [review]
For some reason now GitHub Actions is only running MongoDB 4.0.2 and 6.0.0, but not 5.x.
Not sure why this is happening, but we need to have tests run for 5.x as well.

Otherwise, LGTM. Thanks a lot. 👍

**Comment by hasezoey** [comment]
>  Not sure why this is happening, but we need to have tests run for 5.x as well.

i understand why its happening, will try to fix

**Comment by hasezoey** [comment]
force pushes, because i had to fix the config multiple times (because i forgot to change things)

but i could not find a way to have less runs that this now (at least not in a non-janky way)

**Review by AbdelrahmanHafez — APPROVED** [review]
LGTM, thanks. 👍

**Pull request merged**
