### PR TITLE
types: avoid unnecessary MergeType<> if TOverrides not set, clean up statics and insertMany() type issues

### PR DESCRIPTION
**Pull request by vkarpov15**
**Summary**

#13529 points out some issues with `MergeType`, this PR makes it so that we avoid using `MergeType` in `HydratedDocument<>` where possible.

However, for a future release, we should remove HydratedDocument, and instead rely on inferring the hydrated document type from the schema. Inferring HydratedDocument type from the raw document type isn't possible in general, and relies on `Omit<>`, which is super brittle in TypeScript - breaks on private/protected fields, unions with generics, and other cases.

**Examples**

### CODE REVIEW

**Comment by hasezoey** [comment]
> However, for a future release, we should remove HydratedDocument, and instead rely on inferring the hydrated document type from the schema.

to my knowledge `HydratedDocument` is useful when you want to assign values explicitly and dont have something like typegoose would provide called `DocumentType`
(ie have a type that is guaranteed to be the correct and full Document, with `Require_id`, overrides applied and everything that might be necessary in the future)

**Review by hasezoey — COMMENTED** [review]
Looks good to me, also mostly compiles fine with current typegoose

currently typegoose defines `HydratedDocument<Something, any>`, which makes it incompatible with `HydratedDocument<Something, {}>`, changing to the following helps, but i dont know if this is the best

```ts
TOverrides extends Record<string, never> ?
  Document<unknown, TQueryHelpers, DocType> & Require_id<DocType> :
  IfAny<TOverrides, Document<unknown, TQueryHelpers, DocType> & Require_id<DocType>, Document<unknown, TQueryHelpers, DocType> & MergeType<
    Require_id<DocType>,
    IfAny<TOverrides, {}>
  >>
```

another option (on typegoose's side) would be to remove the `, any` from the `HydratedDocument` call

**Comment by vkarpov15** [comment]
The idea is to make `type HydratedDocument` just pull a generic from a schema or model, instead of attempting to reconstruct the hydrated document from the raw document. In other words, right now we infer the raw document from the schema, then infer the hydrated document type from the raw type. We should instead infer both the raw document type and the hydrated document type from the schema. That will avoid having to `Omit<>`, would also clean up our problem with FlattenMaps in #13523

**Comment by vkarpov15** [comment]
@hasezoey I applied your suggested updates in 8b8f37b, can you please re-review?

**Review by hasezoey — APPROVED** [review]
Looks good to me and compiles and runs without problems in the current latest typegoose

**Comment by orgads** [comment]
Thank you!

**Pull request merged**
