### PR TITLE
Extract aggregate type

### PR DESCRIPTION
**Pull request by Uzlopak**
This PR extracts aggregate, uses the PipelineStage Interfaces everywhere were possible and makes minor changes in the aggregate.js

### CODE REVIEW

**Comment by Uzlopak** [comment]
Resolves also #11594

**Comment by Uzlopak** [comment]
Resolves #11594

**Comment by Uzlopak** [comment]
There seems to be an unrelated bug in the master, which makes the build pipeline red. :D

**Comment by Uzlopak** [comment]
Now it exposes options attribute in types as it was requested by #11594 . I assume that you could actually argue that the main intent of the option method is to be a wrapper of the options object. So I guess that the original issue is that you can only set but not read options.

So we could theoretically set the fields of options to be readonly...

**Review by vkarpov15 — APPROVED** [review]
Thanks :+1:

**Pull request merged**
