### PR TITLE
Updated mongodb dep to 2.1.6 to avoid kerberos error message

### LINKED ISSUE #3860: Message related to kerberos is out to console in 4.4.2
````shell
$ node -e "require('mongoose')"
[TypeError: Cannot read property 'Kerberos' of undefined]
$
````

on nodejs 0.12.9

### PR DESCRIPTION
**Pull request by cartuchogl**
This I think fix #3860

### CODE REVIEW

**Comment by austinkelleher** [comment]
Can we please get a new npm version published @vkarpov15 ? I am experiencing this issue as well.

**Comment by fedu** [comment]
+1

**Comment by alfredopacino** [comment]
I'm sorry I've just reinstalled mongodb, my dependency is set as

>     "mongodb": "^2.1.6",

but I still see the warning

**Comment by Multigence** [comment]
Same here.

+1 [TypeError: Cannot read property 'Kerberos' of undefined] 

Hope a new version comes out soon.

**Comment by GregoryCollett** [comment]
+1

**Comment by juliakozh** [comment]
+1

**Comment by konradjurk** [comment]
+1

**Comment by seamoss** [comment]
+1

**Comment by btushinde** [comment]
+1

**Comment by Gamaroff** [comment]
+1

**Comment by dustintheweb** [comment]
+1

**Comment by mukul-raina** [comment]
+1

**Comment by chenka** [comment]
+1

**Comment by ngcammayo** [comment]
+1

**Comment by antonk52** [comment]
+1

**Comment by akashdeep-singh** [comment]
+1 Getting this issue in mongoose@4.4.2

**Comment by aichholzer** [comment]
:boom: 

```
[TypeError: Cannot read property 'Kerberos' of undefined]
```

`mongoose 4.4.2`

**Comment by cparadeise** [comment]
+1 mongoose@4.4.2

**Comment by maowug** [comment]
This is fixed in mongodb-core 1.3.`1`

https://github.com/christkv/mongodb-core/blob/e0cefa9e6f2dcdc32dc6da1277a5aebf65dfe726/lib/auth/sspi.js#L31

**Comment by alexandrubau** [comment]
+1 mongoose@4.4.2

**Comment by vicmonmena** [comment]
+1

**package.json file**
```
...
"mongodb": "^2.1.4",
"mongoose": "^4.4.2",
...
```

**Comment by mayognaise** [comment]
+1

**Pull request merged**
