### PR TITLE
handleArray should ensure val is an Array.

### PR DESCRIPTION
**Pull request by jloveridge**
It seems reasonable that the `handleArray` helper method should validate that the passed value is in fact an array or coerce it into such rather than try and call `map` on a non-array object. The lack of this protection caused me some grief recently when a single value was accidentally passed in for an `$in` condition.

### CODE REVIEW

**Comment by jloveridge** [comment]
I honestly don't see how these code changes would affect test #1918. Nothing in these changes should affect `$and` handling.

**Comment by vkarpov15** [comment]
Hmm can you add a test for this? Good work otherwise :)

**Comment by jloveridge** [comment]
Sure, I will add a test for the issue later today and update the pull request.

**Comment by jloveridge** [comment]
@vkarpov15 did you want me to add more test cases or is the one that I added sufficient for this to be able to be merged?

**Comment by vkarpov15** [comment]
Nope this is sufficient. Thanks.

**Pull request merged**
