### PR TITLE
lean() for migrating from stream() to cursor()

### PR DESCRIPTION
**Pull request by pyramation**
this should close https://github.com/Automattic/mongoose/issues/4253

### CODE REVIEW

**Comment by nodesocket** [comment]
👍

**Comment by vkarpov15** [comment]
Great job, thanks! :beers:

**Comment by nodesocket** [comment]
What is the timeframe for releasing 4.5.2? This is blocking bug for us. Thanks.

**Comment by vkarpov15** [comment]
@nodesocket will push a release later tonight, sorry for the delay :beers: 🌴

**Pull request merged**
