### PR TITLE
Add support for express-style error handling middleware

### PR DESCRIPTION
**Pull request by vkarpov15**
Re: #2284

### CODE REVIEW

**Comment by Miyou** [comment]
Is this in the latest version? It's not working for me:
```javascript
TestSchema.post('save', function (error, doc, next) {
	console.log(error); //Is actually the document
	next(); //Error "next is not a function"
});
```

**Comment by vkarpov15** [comment]
@Miyou what does TestSchema look like?

**Comment by Miyou** [comment]
Here's an example that reproduces the problem:
```javascript
var mongoose = require('mongoose');

var TestSchema = new mongoose.Schema({
	name: String,
});

TestSchema.post('save', function (error, doc, next) {
	console.log(error); //Is actually the document
	next(); //Error "next is not a function"
});

var Test = mongoose.model('Test', TestSchema);

var test = new Test({
	name: 'test',
});

test.save();
```

**Comment by vkarpov15** [comment]
Try upgrading to 4.5.3, there was a related issue in 4.5.2

**Pull request merged**
