### PR TITLE
add configuration for renovate bot

### LINKED ISSUE #5953: [Discussion] Automate Dependency Upgrades
**Do you want to request a *feature* or report a *bug*?**

infrastructure feature

**What is the current behavior?**

Dependencies are upgraded manually, `dependencies` are updated fairly regularly, `devDependencies` semi-regularly.

**What is the expected behavior?**

This process _could_ be automated to run on a regular schedule or update whenever a new version is released.

**Potential Solutions**

[Renovate](https://renovateapp.com) and [GreenKeeper](https://greenkeeper.io) both can handle automated dependency upgrades.
GreenKeeper has pretty good defaults, and is fast at upgrading, but offers little configuration.
Renovate needs configuration to be set, but is flexible as to when and how it will upgrade dependencies.

**Caveats**

GreenKeeper can become noisy (comment and PR wise) if versions aren't upgraded, renovate has options for [managing noise](https://renovateapp.com/docs/deep-dives/noise-reduction).
PRs still require manual review, renovate offers [automerging](https://renovateapp.com/docs/deep-dives/noise-reduction#automerging), but that requires significant trust in the tests.

**Benefits**

Automate tracking down new versions, which otherwise can be menial and time consuming.

### PR DESCRIPTION
**Pull request by ChristianMurphy**
resolves #5953

**Summary**

Renovate can open a pull request when a newer version of a dependency, outside the allowed semantic version range becomes available.

**Examples**

Here is the example output PRs based off the current dependencies: https://github.com/ChristianMurphy/mongoose/pulls?utf8=%E2%9C%93&q=is%3Apr+chore+deps

renovate can be run by any user on the project with committer access.

```
npm install --global renovate
renovate --token {github access token} Automattic/mongoose
```

Renovate Website: https://renovatebot.com
Renovate Github: https://github.com/renovatebot/renovate

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@vkarpov15 can do, PR updated

**Comment by ChristianMurphy** [comment]
There is also the option to schedule devDependency updates, E.G. one a week or once a month.

**Comment by ChristianMurphy** [comment]
@vkarpov15 since the repo is locked down so the hosted service can't be used.
The easiest way to keep renovate running is to add a cron job.

I use a two hour cycle for repositories I manage, but the schedule is matter of preference :man_shrugging: 
Renovate would need to run with an access token from any team member with commit access.
```
0 */2 * * * renovate --token {access token} Automattic/mongoose
```

**Comment by vkarpov15** [comment]
@ChristianMurphy thanks for the heads up. I set up renovate on an underutilized EC2 instance with a crontab that runs it once/day.

**Pull request merged**
