### PR TITLE
feat(browser): pre-compile mongoose/browser

### LINKED ISSUE #7219: Pre-compile mongoose/browser
So people don't have to merge their webpack config with [Mongoose's recommended config](https://mongoosejs.com/docs/browser.html#webpack). Re: discussion from https://github.com/Automattic/mongoose/issues/6826#issuecomment-435933307

### PR DESCRIPTION
**Pull request by captaincaius**
Fix #7219

**Summary**

Prebuilt mongoose/browser configured in a way that can be consumed in environments that don't have "window" too.  Webpack test also updated to test the exact same webpack config as the build.

**Examples**

### CODE REVIEW

**Comment by captaincaius** [comment]
remade #8238 b/c of accidental merging in of master

**Comment by arpowers** [comment]
great work @captaincaius ... 💥 

Here's my build analysis in Webpack. Using exactly one function (`objectId`) in the browser build but Mongoose (mongoose/browser) is throwing in 160kb just to spite us.

**Comment by captaincaius** [comment]
Woohoo!  It's merged!  Can't wait to switch my project over it.  Thanks!

@arpowers thanks!  You're right that there's some room for progress in the future.  For this PR I didn't wanna get too ambitious, and just wanted to get things to work on the browser-side without the burden of rebuilding it falling on every developer (and having to keep versions in sync, etc).

One thing you mentioned got me thinking - You said 160kB, but from what I recall it was around 300kB.

Either a) your 160kB is the gzipped size, or b) you're not actually using the prebuilt browser file, but mongoose/browser.js directly instead.  The bundle analyzer you show has all of mongoose's guts exposed, so my guess is B.

I'm guessing that means there may be some low-hanging fruit just by optimizing the webpack config to get the 300kB down to 160kB (externalizing some stuff, etc).

**Comment by arpowers** [comment]
@captaincaius thanks for the tips. I'll try your addition and see if it improves things. Thank you!

**Pull request merged**
