### PR TITLE
Fix `this` scope of default functions for DocumentArray and Array

### LINKED ISSUE #6840: No access to "this" in default function for Array type
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**
When trying to set a default on an Array field, the default function doesn't give me access to the current object being created. I want to fill the array differently depending on the other values.
I found a similar issue https://github.com/Automattic/mongoose/issues/6263
But it is recommended to access pre-hooks, which I can't do. I need to have access to the *default* field.
Im using the latest version of mongoose (5.2.7).

Im using the same example as in the mongoose doc http://mongoosejs.com/docs/defaults.html#default-functions-and-this
I just added a field "actors" which is an array.
In releaseDate, I have access to **this** , but not in actors

```
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const schema = new Schema({
	title: String,
	released: Boolean,
	releaseDate: {
		type: Date,
		default: function() {
			console.log("releaseDate: ", this.released);
			if (this.released) {
				return Date.now();
			}
			return null;
		}
	},
	actors: {
		type: [
			{
				name: String,
				age: Number
			}
		],
		default: function() {
			console.log("actors: ", this.released);
			return [
				{
					name: "Test",
					age: 20
				}
			];
		}
	}
});

const Movie = mongoose.model("Movie", schema);

const movie1 = new Movie({ title: "The Terminator", released: true });
const movie2 = new Movie({ title: "The Legend of Conan", released: false });

console.log(movie1);
```

### PR DESCRIPTION
**Pull request by Fonger**
Fix #6840 

**Summary**

DocumentArray ---(this=doc)---> Array ---(no this bind)---> Custom Default Function

**Test plan**

included in this pull request

### CODE REVIEW

**Comment by Fonger** [comment]
@vkarpov15 

Or maybe document this default behavior in website?
https://mongoosejs.com/docs/defaults.html#default-functions-and-this

Currently, it only shows
```
Unless it is running on a query with setDefaultsOnInsert,
a default function's this refers to the document.
```

**Comment by vkarpov15** [comment]
@Fonger you mean document `$runBeforeSetters`? That sounds an awful lot making it part of the public API

**Comment by Fonger** [comment]
@vkarpov15 Just document this behavior by mentioning that in primitive Array, `this` has no initial data unlike DocumentArray and other types have.

**Comment by vkarpov15** [comment]
That sounds like it might be a bug. Can you open up an issue with a repro script @Fonger ?

**Pull request merged**
