### PR TITLE
Use Number.isNaN() instead of global isNaN() w/ polyfill

### PR DESCRIPTION
**Pull request by alexkavon**
The new ES6 Number.isNaN() is much more accurate. I've updated the function to use it, as well as a polyfill for older versions of Node or IE/older browsers for the browser component. I've also added a special use case for 'undefined' (a string) and undefined (undefined) to return undefined, so that fields can still be unset.

Let me know what else I can do to improve this (are there other pieces of code that need updating? do I need to write a test? I'm not sure as this is my first time contributing to mongoose).

### CODE REVIEW

**Comment by vkarpov15** [comment]
This is great work! Couple suggestions to make this better though:

1) Let's not add a property to the global `Number` function, that's an unintentional side effect. Maybe something like:

```javascript
var _isNaN = Number.isNaN || function() { /** polyfill here */ };
```

2) There's a couple other places where mongoose uses `isNaN()`: https://github.com/Automattic/mongoose/blob/9890109c12b3ba80e9e7824fa988857f7788ee2c/lib/schema/operators/bitwise.js#L30, https://github.com/Automattic/mongoose/blob/9890109c12b3ba80e9e7824fa988857f7788ee2c/lib/schema/date.js#L230 that need to be fixed. In the latter case we use `Number.isNaN()` without polyfill because of a mistake in https://github.com/Automattic/mongoose/commit/cc6c2d19e55de3787298ed36174e505f3e1909af, can you fix that too please?

**Comment by alexkavon** [comment]
Of course! I'll get to work.

**Comment by alexkavon** [comment]
@vkarpov15 The places I'm seeing isNaN used are the following:

* lib/schema/date.js
* lib/schema/number.js
* lib/schema/operators/bitwise.js
* test/docs/schematypes.test.js
* bin/mongoose.debug.js
* bin/mongoose.js
* docs/api.html

Do I need to update all of these? Also, when I render the docs in my browser, I'm not able to Ctrl+F the isNaN it talks about, so I'm not sure what it's referring to in docs/api.html (which I assume is the most current docs)

**Comment by vkarpov15** [comment]
Don't worry about bin, that's compiled code. Also don't worry about docs or `test/docs`

**Comment by alexkavon** [comment]
One more thing. Should I just move the new function/polyfill to lib/utils.js? Rather than adding the code to 3 files.

**Comment by vkarpov15** [comment]
@alexkavon yep that would be great

**Comment by alexkavon** [comment]
Okay, should be good to go. Not sure why the build is failing.

**Comment by alexkavon** [comment]
Actually looking more at this, it needs more work. The L#207 if statement needs to be reconfigured since different values are returned differently with Number.isNaN() as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN:
~~~
Number.isNaN(NaN);        // true
Number.isNaN(Number.NaN); // true
Number.isNaN(0 / 0)       // true

// e.g. these would have been true with global isNaN()
Number.isNaN("NaN");      // false
Number.isNaN(undefined);  // false
Number.isNaN({});         // false
Number.isNaN("blabla");   // false

// These all return false
Number.isNaN(true);
Number.isNaN(null);
Number.isNaN(37);
Number.isNaN("37");
Number.isNaN("37.37");
Number.isNaN("");
Number.isNaN(" ");
~~~

**Comment by alexkavon** [comment]
My latest push tackles this issue a bit, but I'm not sure if I like it: https://github.com/alexkavon/mongoose/blob/master/lib/schema/number.js#L217-L219

**Comment by vkarpov15** [comment]
@alexkavon can you fix your branch / remake this PR? Looks like something got very wonky with the commit history. I'll review this more later but let's make sure to reduce accidental backwards breaking changes, I already have my hands full with minimizing the impact of #3856 :)

**Comment by alexkavon** [comment]
I can do that, but I think we should first discuss how to apporach things with Number.isNaN before creating a new PR, just so things don't get lost or taxing to refer to later.

**Comment by vkarpov15** [comment]
Yeah in hindsight, this may be a backwards breaking change in a bunch of cases... I opened up a separate issue above to track, I'll close this PR for now because its unlikely to get merged in the near future re: edge cases.

**Pull request closed without merging**
