### PR TITLE
feat(mongos connection): Support specifying mongos as a connection string query parameter.

### PR DESCRIPTION
**Pull request by burtonjc**
closes https://github.com/Automattic/mongoose/issues/4035

### CODE REVIEW

**Comment by vkarpov15** [comment]
Thanks :beers:

**Comment by burtonjc** [comment]
Awesome, thanks! 🍻

**Comment by vkarpov15** [comment]
Btw @burtonjc do you use mongoose over at waffle.io? I use waffle pretty heavily at my day job and would love to put waffle's logo on the mongoosejs.com home page :)

**Comment by burtonjc** [comment]
We do indeed use mongoose for waffle.io! We would love to have the waffle logo on the mongoosejs.com home page :)

**Comment by burtonjc** [comment]
@vkarpov15 we are always looking for testimonials for our homepage if your day job or mongoosejs would be interested in being featured there.

**Comment by vkarpov15** [comment]
Sure shoot me an email at val@karpov.io with details, I'd be happy to

**Pull request merged**
