### PR TITLE
Fix types resolved from InferSchemaType

### PR DESCRIPTION
**Pull request by HiiiiD**
**Summary**

Currently `InferSchemaType<>` returns weird types when using `Schema.Types.*`, check #12431 for better explanation

**Examples**

### CODE REVIEW

**Review by hasezoey — CHANGES_REQUESTED** [review]
This change seems to break some existing types tests (see test runs), could you maybe fix those and add new ones that this change is meant to address?

Note: in case you dont know how to run those types tests locally:
- install everything with `npm install`
- and run the types test with `npm run test-tsd`

**Comment by HiiiiD** [comment]
Yes, I'm testing right now

**Comment by HiiiiD** [comment]
I've rebased on top of master, but I have an issue that I don't know how to fix
I've tried for an hour to find out why `required: true` with `Schema.Types.Decimal128` breaks the types but I haven't found a solution.
Any clues @hasezoey?

**Comment by hasezoey** [comment]
The following would fix it for now as mentioned in https://github.com/Automattic/mongoose/issues/12431#issuecomment-1256026048, though i dont know why it happens (probably a typescript bug?)

```diff
index 7c0038a869..ff9914217c 100644
--- a/types/inferschematype.d.ts
+++ b/types/inferschematype.d.ts
@@ -38,7 +38,16 @@ declare module 'mongoose' {
    * // result
    * type UserType = {userName?: string}
    */
-  type InferSchemaType<SchemaType> = ObtainSchemaGeneric<SchemaType, 'DocType'>;
+  type InferSchemaType<SchemaType> = ObtainDocType<SchemaType>; // "ObtainDocType" is used over "ObtainSchemaGeneric", because "ObtainSchemaGeneric" would return a modified result
+
+  /**
+   * @summary Obtains the "DocType" generic of a Schema, has to be used because with "ObtainSchemaGeneric" it would return a modified type
+   * @param {TSchema} TSchema A generic of schema type instance
+   */
+  type ObtainDocType<TSchema> =
+    TSchema extends Schema<any, any, any, any, any, any, any, infer DocType>
+      ? DocType
+      : unknown;
 
   /**
    * @summary Obtains schema Generic type by using generic alias.
```

[inferschematype.patch.txt](https://github.com/Automattic/mongoose/files/9632766/inferschematype.patch.txt)

**Comment by HiiiiD** [comment]
I've applied your changes @hasezoey but have failing tests

**Comment by hasezoey** [comment]
i have updated my comment at https://github.com/Automattic/mongoose/issues/12431#issuecomment-1256026048 because it (after some more testing) contained "wrong" information.

it seems like if we dont do `infer TPathTypeKey` but instead `any`, then the `DocType` for the thing this PR is meant to solve, solves it but creates other issues in other places, but as soon as `infer SomeName` is done again for the `TPathTypeKey` generic, then the type this PR is trying to solve, breaks again
but i have no clue what that generic is there for or what it affects or why typescript does not give the correct type

**Review by vkarpov15 — COMMENTED** [review]
I suspect this will be fixed by #12352, I'll check a little later.

**Comment by vkarpov15** [comment]
Confirmed this is fixed by #12352, without any test failures. I'm going to add the test to #12352 and close this issue. Thanks for pointing out this issue :+1:

**Pull request closed without merging**
