### PR TITLE
docs: remove deprecations guide, no longer relevant in Mongoose 7

### PR DESCRIPTION
**Pull request by vkarpov15**
**Summary**

This guide is no longer relevant in Mongoose 7 as was mentioned in #13547 

**Examples**

### CODE REVIEW

**Comment by hasezoey** [comment]
if it is just currently not relevant anymore, how about repurposing it as a general deprecation notice instead of just mongodb driver deprecations? (a replacement to [the wiki, which seems to not be actively used anymore](https://github.com/Automattic/mongoose/wiki/6.0-Deprecation-Warnings))

and while there is nothing to list just say that there is nothing to list (yet)?

**Comment by vkarpov15** [comment]
Given that there's nothing to list right now, I think we should err on the side of removing this page. We can always add it back once we have something to list.

**Comment by vkarpov15** [comment]
Given that there's nothing to list right now, I think we should err on the side of removing this page. We can always add it back once we have something to list.

**Comment by vkarpov15** [comment]
Given that there's nothing to list right now, I think we should err on the side of removing this page. We can always add it back once we have something to list.

**Comment by hasezoey** [comment]
> Given that there's nothing to list right now, I think we should err on the side of removing this page. We can always add it back once we have something to list.

also sounds good to me

PS: i have hidden the duplicate messages that seem to be there by accident

**Review by AbdelrahmanHafez — APPROVED** [review]

**Review by IslandRhythms — APPROVED** [review]
LGTM

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by hasezoey** [comment]
i actually think now that #13572 has been merged, there is a reason to still have the deprecation file, mentioning that `findOneAndUpdate` option `overwrite` is deprecated and `findOneAndReplace` should be used instead

**Comment by vkarpov15** [comment]
Good point @hasezoey , I'll close this and create a new PR to remove the contents of the current deprecation guide and instead add the `overwrite` deprecation there once we have that.

**Pull request closed without merging**
