### PR TITLE
Enhance docs section linking

### PR DESCRIPTION
**Pull request by saveman71**
Using marked's built-in slugify function ensures the links would not be broken.

Manual links are still supported, e.g.
```
   <h3 id="order"><a href="#order">Save/Validate Hooks</a></h3>
```

However note that this syntax doesn't work (didn't work previously either)
```
   ### [Save/Validate Hooks](#order)
```

Also makes the CSS better:
* You can hover any part of the link + the "hidden" side where the icon appears
* Handles h4, h1 and FAQ

Removes as much as possible "manual" links, but some remain (mostly HTML ones I believe, didn't want to check each one that it wouldn't break a link)

### CODE REVIEW

**Comment by saveman71** [comment]
Would this fix #10652 @IslandRhythms ?

**Comment by IslandRhythms** [comment]
Request review from Valeri. The sub section linking has a PR that fixes it. I don't know if he merged it already.

**Comment by saveman71** [comment]
Ah, I tried to look if anything was started and could not find it can you link it ? Also I cannot request a review myself, can you do it please?

**Comment by IslandRhythms** [comment]
https://github.com/Automattic/mongoose/pull/10748

**Comment by saveman71** [comment]
Ah! Well sorry I have undone a bit what you did haha, I wondered why I could not reproduce the issue. At first I just wanted to extand the "link icon" range's hover but got carried away.

**Comment by saveman71** [comment]
Rebased and fixed merge conflict

**Review by vkarpov15 — APPROVED** [review]
Great work, thanks :+1: Sorry for the delay in merging this

**Pull request merged**
