### PR TITLE
Fix: Recursively populate virtual

### PR DESCRIPTION
**Pull request by VCourdy**
See #11700

### CODE REVIEW

**Comment by Uzlopak** [comment]
Thank you  Can you please provide a unit test to avoid future regressions?

**Comment by VCourdy** [comment]
Done !

**Comment by VCourdy** [comment]
I do not reproduce the failed test on my end, does the test failed due to unexpected slowness ?

**Comment by Uzlopak** [comment]
Dont worry about that.

**Review by Uzlopak — APPROVED** [review]
LGTM

**Pull request merged**
