### PR TITLE
Backport empty bulkwrite fix #13684 to Mongoose v6

### PR DESCRIPTION
**Pull request by JavaScriptBach**
**Summary**
Backport #13684 to Mongoose v6.

### CODE REVIEW

**Review by AbdelrahmanHafez — APPROVED** [review]

**Comment by JavaScriptBach** [comment]
Any idea if https://github.com/Automattic/mongoose/actions/runs/5767232250/job/15636643375?pr=13701 is a real failure, or a flake?

**Comment by AbdelrahmanHafez** [comment]
I'm guessing it's a flaky test, I triggered a re-run for the failed jobs.

**Review by vkarpov15 — APPROVED** [review]
Thanks :+1:

**Comment by JavaScriptBach** [comment]
@vkarpov15 May I request you cut a release for v6? I'd like to upgrade to the latest v6 to address a security vulnerability, and I need this fix to avoid regressions. Thanks!

**Comment by vkarpov15** [comment]
@JavaScriptBach sorry for the delay, shipped 6.11.6 earlier today with the fix

**Pull request merged**
