### PR TITLE
fix(types): add collectionName to Collection

### LINKED ISSUE #9630: Typescript  Property 'collectionName' does not exist on type 'Collection'.
running on Version 11.3

```
 error TS2339: Property 'collectionName' does not exist on type 'Collection'.

43         console.log(`${model.collection.collectionName}`);
                                                           ~~~~~~~~~~~~~~
```

thanks in advance.

### PR DESCRIPTION
**Pull request by AbdelrahmanHafez**
fixes #9630

### CODE REVIEW

**Comment by orgads** [comment]
Please refer to my comment on #9630.

**Comment by AbdelrahmanHafez** [comment]
@orgads 
Noted, we'll be shipping the fix for this in v5.11.13.
Can you test with this PR and see if your code compiles?

**Comment by orgads** [comment]
I'll try to test it this afternoon.

**Comment by orgads** [comment]
Still missing for our project:

* On Connection::collection(), `options` should be optional (`options?: mongodb.CollectionCreateOptions`).

The following types from `@types/mongoose` are missing:
```typescript
  export enum ConnectionStates {
    disconnected = 0,
    connected = 1,
    connecting = 2,
    disconnecting = 3,
    uninitialized = 99,
  }

  /** Expose connection states for user-land */
  export var STATES: typeof ConnectionStates;

  type ModelUpdateOptions = QueryOptions;
```

And after all these, I still can't create a schema with a custom object:

```typescript
  const schema = new mongoose.Schema({
    obj: {
      foo: String
    }
  });
```

```
error TS2322: Type '{ foo: StringConstructor; }' is not assignable to type 'string | Function | Function[] | Schema | SchemaTypeOptions<any> | Schema[] | SchemaTypeOptions<any>[]'.
  Object literal may only specify known properties, and 'foo' does not exist in type 'Function | Function[] | Schema | SchemaTypeOptions<any> | Schema[] | SchemaTypeOptions<any>[]'.

12       foo: String
         ~~~~~~~~~~~
```

**Review by vkarpov15 — APPROVED** [review]
Thanks :+1:

**Comment by vkarpov15** [comment]
"I still can't create a schema with a custom object" should be fixed by #9639

However, the `ModelUpdateOptions` change seems irrelevant. Why not just use `QueryOptions` instead?

**Comment by orgads** [comment]
> "I still can't create a schema with a custom object" should be fixed by #9639
> 
> However, the `ModelUpdateOptions` change seems irrelevant. Why not just use `QueryOptions` instead?

I can change to `QueryOptions`, but notice that this breaks existing code. Especially when it's a minor upgrade, I'd expect it to maintain BC.

**Pull request merged**
