### PR TITLE
Updated mongodb-core to latest version and fixed reconnection bug for replica sets

### PR DESCRIPTION
**Pull request by gfzabarino**

### CODE REVIEW

**Comment by gfzabarino** [comment]
This works once the `reconnect` event gets emitted by mongodb-core, which is implemented in https://github.com/christkv/mongodb-core/commit/accc3857b7c15e7fb94699c2baea4f224ade8afd. Regarding this project, the `buffer` property wasn't getting cleared on `reconnect`.

**Comment by vkarpov15** [comment]
Hmm @gfzabarino do you know why all the tests are failing? I don't want to merge until the tests succeed modulo travis flaking, but they're failing consistently right now.

**Comment by gfzabarino** [comment]
I don't know to be honest. As you can see my change is minimum. I tried running tests without it and they were still failing.

**Comment by vkarpov15** [comment]
Ran the tests locally and they succeed so I'm just gonna chalk this up to travis being travis

**Pull request merged**
