### PR TITLE
[WIP] ESLint

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Checks for [possible errors](https://github.com/eslint/eslint/blob/master/docs/rules/README.md#possible-errors).
Check style guide mentioned in [contributing guide](https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md#fixing-bugs--adding-features).

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@vkarpov15 when the contributing guide says `2 space tab`.
Does that mean that 2 spaces is one indent?
or does that mean indent is 1 tab, and tab is rendered as 2 spaces?

**Comment by ChristianMurphy** [comment]
Other possible rules which are not mentioned in Contributing Guide

* Require semicolon at end of statement
* Use `self` to store reference of `this`

**Comment by vkarpov15** [comment]
Require semi-colon = yes. I'm trying to move toward using `_this` instead of `self` so I wouldn't go for the latter rule. Thanks for the excellent work!

**Comment by vkarpov15** [comment]
The linting of examples has done some mighty weird things to the leading commas. Going forward leading commas should be disallowed anyway, so can we just make it get rid of those?

**Comment by ChristianMurphy** [comment]
Sure, should that change just in the examples folder or throughout the whole project?

**Comment by vkarpov15** [comment]
Let's hold off on doing it throughout the project for now - I have a big PR #3186 ready to merge soon and I don't want to deal with too many merge conflicts

**Comment by ChristianMurphy** [comment]
sure thing, should I hold off on doing more linter work until after #3186 is merged?

**Comment by vkarpov15** [comment]
Nah feel free to put in another PR, I just won't merge it until after that's done.

**Comment by ChristianMurphy** [comment]
:+1: will do

**Pull request merged**
