### PR TITLE
added subPopulate functionality

### PR DESCRIPTION
**Pull request by timbur**
Resubmitting PR #2916 from my master branch because I'm a git noob and it's easier this way lol.

### CODE REVIEW

**Comment by vkarpov15** [comment]
Looks the second commit 74fa8f2 broke a lot of existing tests, can you fix that? Also, can you add some tests for this feature so I can see what it's doing?

**Comment by timbur** [comment]
That is really strange how that one line broke the tests... hmmm.  I'll look into it right now.

**Comment by timbur** [comment]
I think that change fixes it.  Will add tests shortly.

**Comment by timbur** [comment]
Sweet!  I actually didn't expect the tests to pass on my first try.  xD

**Comment by timbur** [comment]
@vkarpov15 Is this still scheduled for 4.2?  Or would it be feasible to go ahead and merge it since the tests passed?  If not, I might offer a temporary patch for people who might want to have something as an alternative to `mongoose-deep-select`.

**Comment by vkarpov15** [comment]
Tests passed so I'll put this on the docket for 4.1 :)

**Comment by timbur** [comment]
Sweet!

**Comment by timbur** [comment]
:sweat_smile:

**Pull request merged**
