### PR TITLE
fix: broken link rawResult (findAndModify)

### PR DESCRIPTION
**Pull request by chhiring90**
Fix broken link findAndModify from (node-mongodb-native 2.0 ) to (node-mongodb-native 3.0).

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. The two fields below are mandatory.

If you're making a change to documentation, do **not** modify a `.html` file directly. Instead find the corresponding `.pug` file or test case in the `test/docs` directory.

**Summary**

**Examples**

### CODE REVIEW

**Review by AbdelrahmanHafez — CHANGES_REQUESTED** [review]
Welcome @chhiring90
Congratulations on your first PR 🎉

I can see that we're using the native driver with version 4.3, shouldn't we be using 4.3 `modifyResult` instead?
https://mongodb.github.io/node-mongodb-native/4.3/interfaces/ModifyResult.html

**Comment by chhiring90** [comment]
Thank you very much. I appreciate it. 
I've done the changes as per your suggestion. My apologies for updating depreciated version.
Let me know your advice on it.

**Comment by AbdelrahmanHafez** [comment]
Thanks 👍

**Comment by chhiring90** [comment]
You're welcome 😊.

**Pull request merged**
