### PR TITLE
Fix for #2879

### PR DESCRIPTION
**Pull request by toblerpwn**
This PR fixes Issue #2879 by allowing self-owned nested properties of virtual objects (or any objects?) to be enumerable. (There is also a minor fix for a case where an undefined property crashes the process.)

Suggest also porting this fix to 3.8.x branch (which we still use in production; will file separate PR if this is approved/etc).

### CODE REVIEW

**Comment by vkarpov15** [comment]
Hmm is a50a8c1 actually necessary? Seems like c575d20 should be sufficient.

**Comment by toblerpwn** [comment]
@vkarpov15 - Yes, that is correct; https://github.com/Automattic/mongoose/commit/a50a8c10dd0774af4197d7c88c0aad56b39367aa was my first step to troubleshoot #2879 in my environment (and it was a partial fix), but, when it became clear  https://github.com/Automattic/mongoose/commit/c575d20f19a95cdc1d940510fa7d6aa461c58698 was also needed (or really ALL that was needed), but I just https://github.com/Automattic/mongoose/commit/a50a8c10dd0774af4197d7c88c0aad56b39367aa in place because it has zero functional impact but a positive stability impact (i.e. for future cases that might encounter this issue).

OR, you could argue that it 'covers up' an expected behavior; in either case I am OK to roll back https://github.com/Automattic/mongoose/commit/a50a8c10dd0774af4197d7c88c0aad56b39367aa if you prefer. Let me know!

**Comment by vkarpov15** [comment]
IMO it's covering up an expected behavior, that case should not be happening because a Document **always** has `$__`.

**Comment by toblerpwn** [comment]
@vkarpov15 - OK, reverted the change.

**Pull request merged**
