### PR TITLE
feat(schema): allow using a POJO for `enum` to support TypeScript enums

### LINKED ISSUE #9546: Support passing a TypeScript enum to `enum` validator in schema
Right now you need to use `Object.values()` to get TypeScript enums to work with the `enum` validator:

```typescript
const promotionSchema = new Schema({
   user: { type: Schema.Types.ObjectId, ref: 'User' },
   product: { type: Schema.Types.ObjectId, ref: 'Product' },
   transactionType: {
      type: String,
      default: ETransactionType.Buy,
      enum: Object.values(ETransactionType)
   }
});
```

Would be nice if Mongoose handled the `Object.values()` part automatically and treated `{ foo: 'FOO', bar: 'BAR' }` as equivalent to `['FOO', 'BAR']` for enums.

### PR DESCRIPTION
**Pull request by AbdelrahmanHafez**
fixes #9546 #9535

### CODE REVIEW

**Review by vkarpov15 — APPROVED** [review]
Great work, we'll release this with v5.11 :+1:

**Comment by AbdelrahmanHafez** [comment]
Thank you, that works. 👍

**Comment by joergbaier** [comment]
@AbdelrahmanHafez @vkarpov15 My team began updating our `enum` values to typescript enums. However there is not a way to allow `null` in this case. This is somewhat related to the discussion here https://github.com/Automattic/mongoose/issues/3044

```typescript
enum Color {
  Red = "red",
  Blue = "blue",
  ...
}

const SomeSchema = new Schema({
  color: { type: String, enum: Color },
  ...
});
```

As far as I can tell, there is no way to allow the color field to be nullable with this syntax. Typescript doesn't allow null in the enum and there is not an option to allow it in mongoose. We would need to use the previous syntax in this case (converting the enum to an array and concatenating null).

It looks like typegoose added a `addNullToEnum` option to handle this.
https://github.com/typegoose/typegoose/issues/235

Any thoughts on exposing a nullable option? I imagine that allowing null with `required: false` would not make sense.

**Comment by vkarpov15** [comment]
@joergbaier the syntax you put would allow `color` to be `null`. The issue you posted says the following:

"Mongoose requires to add null to the enum array to allow an empty value to be used, even when required is false."

That statement is incorrect. You don't need to add `null` to the enum.

**Pull request merged**
