### PR TITLE
chore(workflows/test): update deno version to 1.32

### PR DESCRIPTION
**Pull request by hasezoey**
**Summary**

This PR updates the used deno version to 1.32, because 1.32.2 got a port of `node:zlib` implemented in rust (rather than a polyfill?), because it often resulted in `Error during unzip for /binary/mongodb-linux-x86_64-ubuntu2004-6.0.0.tgz: Error: incorrect header check`

hopefully this fixes this problem for deno

[Example run](https://github.com/hasezoey/mongoose/actions/runs/4631765108/jobs/8195024293)

### CODE REVIEW

**Comment by vkarpov15** [comment]
Might just need to upgrade std?

**Comment by hasezoey** [comment]
> Might just need to upgrade std?

already tried locally, but somehow it keeps failing with the same error (no base url)

**Comment by hasezoey** [comment]
well turns out that i was dumb:
- i didnt notice that `test/deno.js` was explicitly defining the std version for `createRequire` (but not for flags)
- deno 1.31 and std 0.177 removed node from std and moved it to be `node:` imported
- deno somehow changed that `process` needed to be explicitly imported (for `process.stdout` modification)

**Review by AbdelrahmanHafez — APPROVED** [review]

**Review by vkarpov15 — APPROVED** [review]
Nice :+1:

**Pull request merged**
