### PR TITLE
types: typeof Query results into invalid syntax of query.d.ts file

### LINKED ISSUE #12688: ts bug: toConstructor(): typeof Query<ResultType, DocType, THelpers, RawDocType>;
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.2

### Node.js version

16.x

### MongoDB server version

5.x

### Typescript version (if applicable)

4.8.4

### Description

somehow this fails now suddenly:
../../node_modules/mongoose/types/query.d.ts(619,34): error TS1144: '{' or ';' expected.
../../node_modules/mongoose/types/query.d.ts(619,45): error TS1005: '>' expected.
../../node_modules/mongoose/types/query.d.ts(619,77): error TS1109: Expression expected.
../../node_modules/mongoose/types/query.d.ts(622,19): error TS1109: Expression expected.
../../node_modules/mongoose/types/query.d.ts(622,41): error TS1109: Expression expected.
../../node_modules/mongoose/types/query.d.ts(622,50): error TS1109: Expression expected.
../../node_modules/mongoose/types/query.d.ts(622,73): error TS1005: '(' expected.
../../node_modules/mongoose/types/query.d.ts(622,114): error TS1109: Expression expected.
../../node_modules/mongoose/types/query.d.ts(622,138): error TS1005: '(' expected.

the change was made already some weeks ago, but the line is definitly wrong:

toConstructor(): typeof Query<ResultType, DocType, THelpers, RawDocType>;

Query is already a Class and therefore typeof should just get removed.

image

change line 619 to 
`toConstructor(): Query<ResultType, DocType, THelpers, RawDocType>;`

fixes it

### Steps to Reproduce

just open the query.d.ts file in your favourite IDE :)

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by simllll**
**Summary**

right now I cannot compile my proecjt, due to https://github.com/Automattic/mongoose/issues/12688

image

### CODE REVIEW

**Comment by simllll** [comment]
@vkarpov15 we are experienceing this issue on more and more projects... please consider this fix

**Comment by hasezoey** [comment]
as i had already noted in https://github.com/Automattic/mongoose/issues/12529#issuecomment-1272516908, `typeof Query` is the correct type, where as just `Query` would be the wrong type.
This is because by default in typescript a type of a class without `typeof` refers to *a instance of the class*, where as with `typeof` it refers to the *constructor / static of a class*

**Review by vkarpov15 — CHANGES_REQUESTED** [review]
It looks like in #12688 the issue is that you're using an older version of TypeScript, v4.6.x. Furthermore, the original issue mentions that this issue shows up in your IDE, not when you actually compile with TypeScript.

Also, as @hasezoey mentioned, the change you proposed is incorrect. We'll investigate and see if there is a better workaround for "this function returns this class" rather than "this function returns an instance of this class" that is compatible with TypeScript 4.6.

`typeof this` works in TypeScript 4.6, but it doesn't work in TypeScript < 4.4. On the other hand, `typeof Query<ResultType, DocType, THelpers, RawDocType>;` works fine in TypeScript < 4.4 but not TypeScript 4.6 :facepalm:

**Comment by vkarpov15** [comment]
Related https://github.com/Automattic/mongoose/commit/86ca62894f5e5a528f924910acabc3d85483ba9c

**Comment by simllll** [comment]
I will investigate on my site, as we actually use TS 4.8... something seems to install an old TS Version.. anyways, the issue is like you said and my fix is wrong, you can close my PR.

**Pull request closed without merging**
