### PR TITLE
#3628 Mapreduce should return es6 promise

### PR DESCRIPTION
**Pull request by dougmolineux**
I took a shot at making Mapreduce return an ES6 Promise. Please let me know any feedback / problems / opinions.

Thank you

### CODE REVIEW

**Comment by dougmolineux** [comment]
It appears that some checks fails, I will investigate them

**Comment by vkarpov15** [comment]
Great work, thanks! Just one minor comment, otherwise will merge :)

**Comment by dougmolineux** [comment]
Very good, I understand, thank you! I will add the callback tests back in, and then add new ones that use the then's

**Comment by dougmolineux** [comment]
Hmm looks like the tests passed intially but then failed after committing some comments, not sure how that happened

**Comment by vkarpov15** [comment]
Don't worry, tests are flakey on Travis, false failures happen pretty regularly.

**Comment by vkarpov15** [comment]
merged into https://github.com/Automattic/mongoose/tree/4.4

**Comment by dougmolineux** [comment]
Thank you Valeri! Have a great weekend :)

**Pull request closed without merging**
