### PR TITLE
perf: speed up mapOfSubdocs benchmark by 4x by avoiding unnecessary O(n^2) loop in getPathsToValidate()

### PR DESCRIPTION
**Pull request by vkarpov15**
**Summary**

Flame graph helped identify that most of the time was spent in the following loop. With a faster implementation that doesn't loop through all modified paths for every subdocument, Mongoose is now 3-4x faster on the mapOfSubdocs benchmark.

```
for (const subdoc of subdocs) {
  for (const p of paths) {
    if (p == null || p.startsWith(fullPathToSubdoc + '.')) {
      paths.delete(p);
    }
  }
}
```

Before this change:

```
{
  "Average save time ms": 439.4
}
```

After this change:

```
{
  "Average save time ms": 145.8
}
```

Flamegraph now looks a bunch more reasonable too:

image

I think we can now mark #13191 and #13271 as fixed, because `$__reset()` is no longer a bottleneck and between this PR and #13280 Mongoose is now more than 10x faster on this particular benchmark.

**Examples**

### CODE REVIEW

**Review by hasezoey — APPROVED** [review]
LGTM, is this only for 6.x or will this be added to 7.x too?

**Comment by vkarpov15** [comment]
We still merge everything from 6.x back into master, so this will end up in the next 7.x release too.

**Review by Uzlopak — COMMENTED** [review]
LGTM
Awesome

**Review by Uzlopak — APPROVED** [review]

**Review by AbdelrahmanHafez — APPROVED** [review]
Nice! LGTM, thanks! 👍

**Pull request merged**
