### PR TITLE
fix(model): make exists(...) return lean document with `_id` or `null` instead of boolean

### PR DESCRIPTION
**Pull request by AbdelrahmanHafez**
re #11138

### CODE REVIEW

**Comment by Uzlopak** [comment]
This will definitely be a breaking change. I know a codebase where exists is checked to be a resolved boolean.

**Comment by AbdelrahmanHafez** [comment]
@Uzlopak 
It is a breaking change that was supposed to land on mongoose v6.0, it didn't land due to a bug, but it was mentioned in the changelog, and people would be expected to change their code accordingly.

@vkarpov15 What do you think is the best action here? I think we can ship it in a minor release and make a note about it.

**Comment by vkarpov15** [comment]
I'll merge this into the 6.2 branch in the interest of caution. This is a messy case where the docs say one thing, the TypeScript bindings say something else, and the actual behavior is inconsistent between the two. So let's put this in a minor release to minimize risk, but also make it so the actual behavior and TS bindings match what is in our docs.

**Comment by Maximusya** [comment]
https://mongoosejs.com/docs/migrating_to_6.html is still missing this breaking change.
Though it hit us not when migrating from 5 to 6(.1), but when migrating from 6.1 to 6.2

**Pull request merged**
