### PR TITLE
make ValidatorError.properties not enumerable

### PR DESCRIPTION
**Pull request by Fonger**
Resolve issue #3925

### CODE REVIEW

**Comment by vkarpov15** [comment]
Can you define this on the prototype like you showed in https://github.com/Automattic/mongoose/issues/3925 ? Better performance that way.

**Comment by Fonger** [comment]
@vkarpov15 I can't use that way. It will fail the test because it will erase the value of properties in constructor.

```js
          var M = mongoose.model('gh-2132', schema, 'gh-2132');

          var m = new M({x: 'a'});
          m.validate(function(err) {
            assert.equal('Error code 25', err.errors.x.toString());
            assert.equal(25, err.errors.x.properties.errorCode);
            done();
          });
```

```
  1462 passing (17s)
  1 failing

  1) schema validation messages are customizable supports custom properties (gh-2132):
     Uncaught TypeError: Cannot read property 'errorCode' of undefined
      at test/schema.validation.test.js:649:53
      at lib/document.js:1090:19
      at complete (lib/document.js:1164:7)
      at lib/document.js:1195:20
      at ObjectId.SchemaType.doValidate (lib/schematype.js:682:12)
      at lib/document.js:1191:9
```

**Comment by vkarpov15** [comment]
Will review more closely in a bit. I'd rather not do `defineProperty` transactionally, but if there's no other way this should work too.

**Comment by vkarpov15** [comment]
@Fonger found a way to do this by defining the property on the prototype. `defineProperty()` is very slow and I'd rather not do that for every ValidatorError.

**Comment by Fonger** [comment]
@vkarpov15 thanks :beers:

**Pull request closed without merging**
