### PR TITLE
Update model.js

### PR DESCRIPTION
**Pull request by basileos**
**Summary**

Fixed issue #5218 -  possible __v: undefined condition in where clause, which breaks documents saving in some cases.
**Test plan**
Test script from bug report works as expected with this version

### CODE REVIEW

**Comment by vkarpov15** [comment]
Tests break because `if (!value)` will trigger in cases where `__v` is 0 as well as undefined. I suggest you do `if (value != null)` instead, because `v == null` is equivalent to `v === undefined || v === null`

**Comment by vkarpov15** [comment]
Thanks :beers:

**Comment by maganap** [comment]
Is it possible this problem is still happening?
Concurrent requests from client to save the same doc, throws `Version Error: No matching document found for id <_id>`.

mongoose: v4.13.6
node: v6.11.0
mongoDB: v3.4.5

About 10 concurrent calls, only some fail (3 in this case):
```
[2018-01-03T12:56:11.887Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2eb44a7b96dfc725153 / ref: qTVFEdwA/hd1.jpeg (module=lib_utils)
[2018-01-03T12:56:11.889Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2eb44a7b96dfc725154 / ref: tU74lU1D/hd1.jpeg (module=lib_utils)
[2018-01-03T12:56:12.013Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2ec44a7b96dfc725155 / ref: xdkIPWfC/hd2.jpeg (module=lib_utils)
[2018-01-03T12:56:12.014Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2ec44a7b96dfc725156 / ref: fTAfAvHt/hd1.jpeg (module=lib_utils)
[2018-01-03T12:56:13.277Z] ERROR: a2s/28156 on a2server-2: No matching document found for id "5a4cd2ea44a7b96dfc725150"
    Error
        at model.wrappedPointCut [as save] (/mnt/a2server-data/apps/TourMe/node_modules/mongoose/lib/services/model/applyHooks.js:131:29)
        at Model.findOne.then.doc (/mnt/a2server-data/apps/TourMe/app/lib/utils.js:221:22)
        at process._tickDomainCallback (internal/process/next_tick.js:135:7)
[2018-01-03T12:56:13.346Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2ed44a7b96dfc725157 / ref: Ij3B4Ybh/hd2.jpeg (module=lib_utils)
[2018-01-03T12:56:13.401Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2ed44a7b96dfc725158 / ref: rRESMcga/hd2.jpeg (module=lib_utils)
[2018-01-03T12:56:13.403Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2ed44a7b96dfc725159 / ref: UqUQscfa/hd1.jpeg (module=lib_utils)
[2018-01-03T12:56:13.893Z] ERROR: a2s/28156 on a2server-2: No matching document found for id "5a4cd2ea44a7b96dfc725150"
    Error
        at model.wrappedPointCut [as save] (/mnt/a2server-data/apps/TourMe/node_modules/mongoose/lib/services/model/applyHooks.js:131:29)
        at Model.findOne.then.doc (/mnt/a2server-data/apps/TourMe/app/lib/utils.js:221:22)
        at process._tickDomainCallback (internal/process/next_tick.js:135:7)
[2018-01-03T12:56:13.900Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2ed44a7b96dfc72515a / ref: SVmtIuj7/hd2.jpeg (module=lib_utils)
[2018-01-03T12:56:13.988Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2ed44a7b96dfc72515b / ref: 9SJs5FRZ/hd1.jpeg (module=lib_utils)
[2018-01-03T12:56:14.179Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2ee44a7b96dfc72515c / ref: HHKHAxRC/hd2.jpeg (module=lib_utils)
[2018-01-03T12:56:15.262Z] ERROR: a2s/28156 on a2server-2: No matching document found for id "5a4cd2ea44a7b96dfc725150"
    Error
        at model.wrappedPointCut [as save] (/mnt/a2server-data/apps/TourMe/node_modules/mongoose/lib/services/model/applyHooks.js:131:29)
        at Model.findOne.then.doc (/mnt/a2server-data/apps/TourMe/app/lib/utils.js:221:22)
        at process._tickDomainCallback (internal/process/next_tick.js:135:7)
[2018-01-03T12:56:15.300Z] ERROR: a2s/28156 on a2server-2: No matching document found for id "5a4cd2ea44a7b96dfc725150"
    Error
        at model.wrappedPointCut [as save] (/mnt/a2server-data/apps/TourMe/node_modules/mongoose/lib/services/model/applyHooks.js:131:29)
        at Model.findOne.then.doc (/mnt/a2server-data/apps/TourMe/app/lib/utils.js:221:22)
        at process._tickDomainCallback (internal/process/next_tick.js:135:7)
[2018-01-03T12:56:15.417Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2ef44a7b96dfc72515d / ref: gE8P3tlD/hd2.jpeg (module=lib_utils)
[2018-01-03T12:56:15.418Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2ef44a7b96dfc72515e / ref: HS9D1dTm/hd1.jpeg (module=lib_utils)
[2018-01-03T12:56:15.509Z] TRACE: a2s/28156 on a2server-2: setPicture (tour) -> _id: 5a4cd2ea44a7b96dfc725150 / pid: 5a4cd2ef44a7b96dfc72515f / ref: bAWwQMSj/hd1.jpeg (module=lib_utils)
```

**Comment by vkarpov15** [comment]
@maganap are you updating arrays in the document? Mongoose has versioning enabled by default to prevent, say, two documents concurrently trying to remove the 1st element of an array.

**Comment by maganap** [comment]
@vkarpov15 Yep, I'm updating an array.  I understand this is just a race condition caused by concurrent find->save, so it's great mongoose does not overwrite with an old array.  I just guess the text `No matching document found for id` was misleading since a doc with that _id does exist.

In any case, I'm currently catching the error on save() and retrying based on the error text but... I wouldn't like to rely on a string that could change at any time. Do you have any suggestions on how to handle this situation more properly?  Thx in advance.

**Comment by vkarpov15** [comment]
You can check `error instanceof mongoose.Error.VersionError` or `error.name === 'VersionError'`, both of those are more robust than checking the string. I agree the error is a bit misleading, I added an error to add the version number to the error message so its clear it is checking the version number.

**Pull request merged**
