### PR TITLE
fix(dependencies): upgrade mongodb version

### PR DESCRIPTION
**Pull request by donnanicolas**
In versions 2.0.34 to 2.1.18 of the mongo driver there seems to be an issue with how pools are handled, the queries are really slow, and the CPU and memory values of the servers (application and database) are at normal levels (not starved, not even under heavy work). See this Jira Issue for more information [Some clients are experiencing slow query times after 2.0.33](https://jira.mongodb.org/browse/NODE-730?jql=project%20%3D%20NODE).

We are trying with the new version of the mongodb driver, and everything seems to be running okay, but until tomorrow (to test the fix for a long time) I cannot be sure that if correctly fixes it.

Here is a graphic of the difference
screen_shot_2016-07-18_at_15_29_19

### CODE REVIEW

**Comment by donnanicolas** [comment]
I'm trying to fix the errors that come up, but I haven't got enough knowledge to do so. There is one issue that I fixed by changing the way the assertion is done, in `model.test.js` (haven't uploaded it, because I don't know why the check would fail in the current version

From this:
```
assert.equal(found._id.id, created._id.id);
```

To this:
```
assert.ok(found._id.equals(created._id), 'Expected ' + found._id + ' to equal ' + created._id);
```
Some seem to be failing because of the way the `db.on('error', ...)` callback receives the parameters, it gets a circular object, this is what I got after some touches:

```
Error: done() invoked with non-Error: {"id":4,"s":{"options":{"disconnectHandler":{"s":{"storedOps":[],"storeOptions":{"force":false,"bufferMaxEntries":-1},"topology":{"domain":null,"_events":{},"_eventsCount":8,"s":{"sCapabilities":null,"clonedOptions":{"reconnect":true,"emitError":true,"size":5,"ssl":true,"rejectUnauthorized":true},"options":{"native_parser":false,"w":2,"fsync":true,"readPreference":"nearest","forceServerObjectId":false}}}},"length":0},"reconnect":true,"emitError":true,"size":5,"ssl":true,"rejectUnauthorized":true},"bson":{},"logger":{"className":"Mongos"},"seedlist":[{"host":"localhost","port":27017}],"haInterval":10000,"index":0,"debug":false,"localThresholdMS":15},"authProviders":{"mongocr":{"authStore":[]},"x509":{"authStore":[]},"plain":{"authStore":[]},"gssapi":{"authStore":[]},"sspi":{"authStore":[]},"scram-sha-1":{"authStore":[],"id":36}},"state":"destroyed","connectingProxies":[],"connectedProxies":[],"disconnectedProxies":[{"domain":null,"_events":{},"_eventsCount":6,"id":43,"s":{"options":{"reconnect":false,"emitError":true,"size":5,"ssl":true,"rejectUnauthorized":true,"host":"localhost","port":27017,"monitoring":false,"inTopology":true,"native_parser":false,"w":2,"fsync":true,"readPreference":"nearest","forceServerObjectId":false,"bson":{}},"logger":{"className":"Server"},"pool":{"domain":null,"_events":{},"_eventsCount":7,"options":{"host":"localhost","port":27017,"size":5,"connectionTimeout":30000,"socketTimeout":30000,"keepAlive":true,"keepAliveInitialDelay":0,"noDelay":true,"ssl":true,"checkServerIdentity":false,"ca":null,"cert":null,"key":null,"passPhrase":null,"rejectUnauthorized":true,"promoteLongs":true,"reconnect":false,"reconnectInterval":1000,"reconnectTries":30,"emitError":true,"monitoring":false,"inTopology":true,"native_parser":false,"w":2,"fsync":true,"readPreference":"nearest","forceServerObjectId":false},"id":36,"retriesLeft":30,"reconnectId":null,"logger":{"className":"Pool"},"state":"disconnected","availableConnections":[],"inUseConnections":[],"connectingConnections":[],"executing":false,"queue":[],"authenticating":false,"loggingout":false,"nonAuthenticatedConnections":[],"authenticatingTimestamp":null,"numberOfConsecutiveTimeouts":0},"monitoring":false,"inTopology":true,"monitoringInterval":5000,"topologyId":-1},"ismaster":null,"lastIsMasterMS":-1,"monitoringProcessId":null,"initalConnect":false,"wireProtocolHandler":{},"_type":"server"}],"authenticating":false,"index":0,"haTimeoutId":{"0":null,"_called":false,"_idleTimeout":-1,"_idlePrev":null,"_idleNext":null,"_idleStart":1817,"_onTimeout":null,"_repeat":null},"ismaster":null,"lowerBoundLatency":1.7976931348623157e+308,"domain":null,"_events":{},"_eventsCount":6}
```

I would glady help if you can guide me a little bit

**Comment by donnanicolas** [comment]
The issue is fixed with the new mongo driver version, is there any way this gets accepted?? This issue was is really troublesome, and for the moment we are using our fork in production.

**Comment by vkarpov15** [comment]
@donnanicolas I've been investigating upgrading, but mongoose's test suite fails miserably with driver 2.2.x. Not sure why yet, even with fixing the assert issue you mentioned there's still a lot of failures that I haven't been able to explain.

**Comment by vkarpov15** [comment]
Fixed by #4363

**Pull request closed without merging**
