### PR TITLE
fix(document): add index param to eachAsync fn

### PR DESCRIPTION
**Pull request by krosenk729**
**Summary**

Fix for https://github.com/Automattic/mongoose/issues/13152

**Examples**

### CODE REVIEW

**Review by AbdelrahmanHafez — CHANGES_REQUESTED** [review]
LGTM, can you please add a test in `test/typescript` to prevent that from being accidentally deleted?

**Comment by krosenk729** [comment]
yes thanks for the fast review @AbdelrahmanHafez -- added a test

**Review by vkarpov15 — APPROVED** [review]
Thanks :+1:

I noticed in #13152 you're using Mongoose 6.6.1. Is there anything blocking you from upgrading to Mongoose 7? Since this PR is against master branch, it will go into 7.0.2. But we can also cherry pick this into 6.x.

**Comment by krosenk729** [comment]
> Thanks 👍
> 
> I noticed in #13152 you're using Mongoose 6.6.1. Is there anything blocking you from upgrading to Mongoose 7? Since this PR is against master branch, it will go into 7.0.2. But we can also cherry pick this into 6.x.

@vkarpov15  a cherry pick would be much much appreciated. our last upgrade was a little complicated, so we're still gathering resources to devote to another major version bump

**Comment by vkarpov15** [comment]
@krosenk729 it looks like this fix was already applied to 6.x here: https://github.com/Automattic/mongoose/pull/13162 . Upgrade to 6.10.3 for the fix :+1:

**Pull request merged**
