### PR TITLE
gh-1936 - dynamic messages for validators with callback

### PR DESCRIPTION
**Pull request by geronime**
Solves #1936

See also #2113

### CODE REVIEW

**Comment by geronime** [comment]
Tests failed for 0.10 in Travis but not caused by this change as far as I can see:

```
  1) aggregate:  near works with discriminators (gh-3304):
     TypeError: Cannot call method 'aggregate' of undefined
      at /home/travis/build/Automattic/mongoose/lib/aggregate.js:470:8
      at new Promise.ES6 (/home/travis/build/Automattic/mongoose/lib/promise.js:45:3)
...
  2) model create() creates in parallel:
     Error: timeout of 1000ms exceeded
      at null.<anonymous> (/home/travis/build/Automattic/mongoose/node_modules/mocha/lib/runnable.js:139:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
  3) model indexes do not trigger "MongoError: cannot add index with a background operation in progress" (gh-1365) LONG:
     Error: timeout of 45000ms exceeded
      at null.<anonymous> (/home/travis/build/Automattic/mongoose/node_modules/mocha/lib/runnable.js:139:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```

**Comment by vkarpov15** [comment]
Yeah travis build can be flakey. Thanks, will merge for 4.2

**Comment by vkarpov15** [comment]
Merged and released. Thanks @geronime  :beers:

**Comment by kog13** [comment]
@geronime its been a minute, but also wanted to say thank you for this one!

**Pull request merged**
